FROM python:3.8.3-alpine

WORKDIR $HOME_PROJ_PATH

RUN chmod 0775 "$HOME_PROJ_PATH/src/bash/scripts/docker-init-${MODULE}.sh"

CMD exec /bin/bash -c "$HOME_PROJ_PATH/src/bash/scripts/docker-init-${MODULE}.sh"
