FROM python:3.8.3-alpine

# install backend-utils
RUN apk update && apk upgrade && apk add --no-cache \
    build-base gcc openssl-dev python3-dev libmagic ttf-freefont \
    python3-dev jpeg-dev zlib-dev coreutils libffi-dev util-linux

