FROM python:3.8.3-alpine

# START ::: copy-proj-dir

COPY --chown=$APPUSR:$APPGRP . ${HOME_PROJ_PATH}
COPY --chown=$APPUSR:$APPGRP ./src/bash/run/run.sh ${HOME_PROJ_PATH}/src/bash/run/run.sh

# Create the 'run' symlink
RUN ln -sfn ${HOME_PROJ_PATH}/src/bash/run/run.sh ${HOME_PROJ_PATH}/run

# STOP  ::: copy-proj-dir
